services:
  db:
    image: postgres:16
    container_name: sui_payment_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sui_payment
    ports:
      - "5432:5432"
    volumes:
      - sui_payment_pgdata:/var/lib/postgresql/data

volumes:
  sui_payment_pgdata:

